function write_report_macros(path, m)
%WRITE_REPORT_MACROS  Emit the simulation results as LaTeX macros.
%
%   WRITE_REPORT_MACROS('docs/report/metrics.tex', metrics)
%
%   Every number quoted in the report is defined here and used as \mDVtot,
%   \mJTwoMiss and so on. The report therefore cannot drift out of step with
%   the build: change the physics, rebuild, and the PDF recompiles with the new
%   figures. Hand-typing results into a report is how a document ends up
%   claiming a value the code stopped producing three commits ago.

fid = fopen(path, 'w');
if fid < 0
    error('write_report_macros:open', 'Cannot write %s', path);
end
closer = onCleanup(@() fclose(fid));

fprintf(fid, '%% Generated by lib/util/write_report_macros.m -- do not edit.\n');
fprintf(fid, '%% Build stamp: %s\n\n', char(datetime('now','Format','yyyy-MM-dd HH:mm')));
fprintf(fid, '\\newcommand{\\mBuildDate}{%s}\n', char(datetime('now','Format','d MMMM yyyy')));

defs = {
 'mDVone',        'dV1_ms',          '%.2f'
 'mDVtwo',        'dV2_ms',          '%.2f'
 'mDVtot',        'dVtot_ms',        '%.2f'
 'mSMA',          'a_km',            '%.1f'
 'mEcc',          'e',               '%.4f'
 'mTOF',          'dt_tof_s',        '%.2f'
 'mTOFmin',       'dt_tof_min',      '%.2f'
 'mTwait',        't_wait_s',        '%.0f'
 'mTwaitH',       't_wait_h',        '%.2f'
 'mTmissionH',    't_mission_h',     '%.2f'
 'mLeadDeg',      'dtheta_H_deg',    '%.2f'
 'mKeplerErr',    'errLM_max_m',     '%.2e'
 'mKeplerErrMm',  'errLM_max_mm',    '%.3f'
 'mMissKep',      'miss_num_m',      '%.1e'
 'mDrZero',       'dr0_norm_m',      '%.1f'
 'mDvZero',       'dv0_norm_ms',     '%.4f'
 'mDriftKm',      'drift_max_km',    '%.2f'
 'mDVhold',       'dV_hold_ms',      '%.3f'
 'mDVdock',       'dV_dock_ms',      '%.4f'
 'mDVprox',       'dV_prox_ms',      '%.3f'
 'mNlSep',        'nl_final_sep_m',  '%.1f'
 'mDtTr',         'dt_tr_s',         '%.0f'
 'mMissJtwo',     'miss_J2_km',      '%.2f'
 'mMissJtwoTB',   'miss_J2_3B_km',   '%.2f'
 'mMissTB',       'miss_3Bonly_m',   '%.1f'
 'mDVmcc',        'dV_mcc_ms',       '%.1f'
 'mAkep',         'a_kep',           '%.3f'
 'mAJtwo',        'a_J2',            '%.2e'
 'mATB',          'a_3B',            '%.2e'
 'mCRmiss',       'miss_m',          '%.1e'
 'mCRextra',      'dV_extra_mms',    '%.2f'
 'mCRtof',        'tof_cr3bp_s',     '%.2f'
 'mCRtofShift',   'tof_shift_s',     '%+.2f'
 'mReach',        'reach_m',         '%.1f'
 'mArmMass',      'mass_kg',         '%.0f'
 'mTauMax',       'tau_max_Nm',      '%.1f'
 'mDualRes',      'dualityResidual_max', '%.1e'
 'mIKres',        'ik_res_mm',       '%.2f'
 'mIKiters',      'ik_iters',        '%d'
 'mIKtwoRes',     'ik2_res_mm',      '%.2f'
 'mNfig',         'nFigures',        '%d'
 'mReelSec',      'showreelSeconds', '%.0f'
 % --- pass 4 -------------------------------------------------------------
 'mMissTwoBody',  'miss_LM_MS_twobody', '%.4f'
 'mMissKepMm',    'miss_num_vs_kepler_mm', '%.3f'
 'mMccReal',      'dV_mcc_ms',       '%.3f'
 'mMccNaive',     'dV_mcc_naive_ms', '%.1f'
 'mMccMid',       'mcc_dV_mid',      '%.3f'
 'mMccResid',     'mcc_resid_m',     '%.3f'
 'mMccLever',     'mcc_lever_h',     '%.2f'
 'mMccTransfer',  'mcc_midtransfer', '%.1f'
 'mJtwoRateRel',  'j2_rate_rel_R1',  '%.1e'
 'mJtwoExcess',   'j2_excess_R1',    '%.2e'
 'mGlossA',       'gloss_TW01',      '%.3f'
 'mGlossB',       'gloss_TW03',      '%.4f'
 'mGlossC',       'gloss_TW10',      '%.4f'
 'mGlossTb',      'gloss_tb01',      '%.0f'
 'mMCn',          'mc_nDraw',        '%d'
 'mMCpFive',      'mc_hold_p05',     '%.3f'
 'mMCpFifty',     'mc_hold_p50',     '%.3f'
 'mMCpNinetyFive','mc_hold_p95',     '%.3f'
 'mFamSpread',    'fam_spread_mms',  '%.0f'
 'mFamN',         'fam_nClosed',     '%d'
 'mFamMinDV',     'fam_minDV_mms',   '%+.2f'
 'mFamMinTof',    'fam_minDV_dtof',  '%+.1f'
 'mFamRefDV',     'fam_ref_mms',     '%+.2f'
 'mFamRefTof',    'fam_ref_dtof',    '%+.1f'
 'mCRsigned',     'dV_signed_mms',   '%+.2f'
};

% A couple of convenience quantities the parts do not store directly.
if isfield(m, 'dt_tof_s'), m.dt_tof_min = m.dt_tof_s / 60; end
if isfield(m, 'errLM_max_m'), m.errLM_max_mm = m.errLM_max_m * 1e3; end
if isfield(m, 'miss_num_vs_kepler'), m.miss_num_vs_kepler_mm = m.miss_num_vs_kepler * 1e3; end
if ~isfield(m, 'showreelSeconds'), m.showreelSeconds = 87; end

for k = 1:size(defs, 1)
    name = defs{k,1};
    fld  = defs{k,2};
    if isfield(m, fld) && isnumeric(m.(fld)) && isscalar(m.(fld)) && isfinite(m.(fld))
        val = texnum(sprintf(defs{k,3}, m.(fld)));
    else
        val = '\textbf{?}';
    end
    fprintf(fid, '\\newcommand{\\%s}{%s}\n', name, val);
end
end

% ------------------------------------------------------------------ helpers --
function s = texnum(s)
%TEXNUM  Turn C-style exponent notation into proper LaTeX.
%   sprintf('%.1e', 4.77e-8) gives "4.8e-08", which typesets inside math mode
%   as "4.8e - 08" with the exponent read as a subtraction. Every macro in this
%   file is used inside $...$, so the conversion has to happen here.
tok = regexp(s, '^([-+]?[\d.]+)[eE]([-+]?)0*(\d+)$', 'tokens', 'once');
if isempty(tok)
    return
end
mant = tok{1};
sgn  = tok{2};
expo = tok{3};
if strcmp(sgn, '+'), sgn = ''; end
% \ensuremath so the same macro works in a table cell and inside $...$ alike.
% Without it a value used outside math mode fails on \times, and wrapping the
% call sites by hand would defeat the point of generating them.
if strcmp(mant, '1')
    s = sprintf('\\ensuremath{10^{%s%s}}', sgn, expo);
else
    s = sprintf('\\ensuremath{%s\\times 10^{%s%s}}', mant, sgn, expo);
end
end
