function outPath = make_lander_schematic(C)
%MAKE_LANDER_SCHEMATIC  Figure 18: an original two-stage lander diagram.
%   Drawn entirely from patches and lines. The source report this project
%   grew out of used an Apollo photograph; a schematic avoids the copyright
%   question completely and labels the parts that matter to the simulation.

S = style();
fig = new_figure(1500, 950);
ax = axes('Parent', fig, 'Position', [0.06 0.07 0.60 0.86]);
style_axes(ax, 'Two-stage crewed lander, ascent configuration', 'x [m]', 'z [m]');
axis(ax, 'equal');

% Descent stage: the platform that stays on the surface.
patch(ax, [-2.2 2.2 2.0 -2.0], [0 0 1.7 1.7], S.dim*0.55, ...
      'EdgeColor', S.dim, 'LineWidth', 1.6, 'FaceAlpha', 0.85);
% Ascent stage: crew cabin plus the single-string ascent engine.
patch(ax, [-1.5 1.5 1.25 -1.25], [1.7 1.7 3.6 3.6], S.LM*0.65, ...
      'EdgeColor', S.LM, 'LineWidth', 1.8, 'FaceAlpha', 0.9);
patch(ax, [-0.9 0.9 0.6 -0.6], [3.6 3.6 4.5 4.5], S.LM*0.8, ...
      'EdgeColor', S.LM, 'LineWidth', 1.8, 'FaceAlpha', 0.9);
% Docking / grapple interface on top.
patch(ax, [-0.35 0.35 0.35 -0.35], [4.5 4.5 4.9 4.9], S.hold, ...
      'EdgeColor', 'none', 'FaceAlpha', 0.95);
% Ascent engine bell, hanging below the cabin.
patch(ax, [-0.35 0.35 0.75 -0.75], [1.7 1.7 0.75 0.75], S.warn*0.8, ...
      'EdgeColor', S.warn, 'LineWidth', 1.6, 'FaceAlpha', 0.9);

% Four legs, two visible on each side in this projection.
for sx = [-1 1]
    for dx = [1.0 1.9]
        plot(ax, sx*[dx dx+1.15], [0.35 -1.25], '-', 'Color', S.dim, 'LineWidth', 3.5);
        plot(ax, sx*(dx+1.15) + [-0.32 0.32], [-1.25 -1.25], '-', ...
             'Color', S.dim, 'LineWidth', 5);
    end
end
plot(ax, [-5 5], [-1.25 -1.25], '-', 'Color', S.moonEdge, 'LineWidth', 2);
patch(ax, [-5 5 5 -5], [-1.25 -1.25 -2.2 -2.2], S.moonFace*0.6, ...
      'EdgeColor', 'none', 'FaceAlpha', 0.6);

% Centre of mass and thrust axis: the pair that makes ascent control hard.
plot(ax, 0, 2.35, 'o', 'MarkerSize', 13, 'MarkerFaceColor', S.transfer, 'MarkerEdgeColor','none');
plot(ax, [0 0], [0.6 4.9], ':', 'Color', S.transfer, 'LineWidth', 1.6);
plot(ax, 0.28, 2.35, 'x', 'MarkerSize', 14, 'Color', S.MS, 'LineWidth', 2.5);

labels = { 0.55, 4.70, '  docking / grapple interface', S.hold;
           1.60, 4.05, '  crew cabin', S.LM;
           1.65, 2.60, '  ascent stage (propellant + avionics)', S.LM;
           2.30, 0.85, '  descent stage, stays on the surface', S.dim;
           0.85, 1.20, '  ascent engine (single string)', S.warn;
           0.15, 2.35, '  CoM, shifting as propellant burns', S.transfer };
for k = 1:size(labels,1)
    text(ax, labels{k,1}, labels{k,2}, labels{k,3}, 'Color', labels{k,4}, ...
         'FontName', S.font, 'FontSize', S.fsSmall);
end
xlim(ax, [-5.2 5.2]); ylim(ax, [-2.3 5.6]);

ax2 = axes('Parent', fig, 'Position', [0.68 0.07 0.30 0.86]);
set(ax2, 'Color', 'none', 'XLim', [0 1], 'YLim', [0 1], 'Visible', 'off');
hold(ax2, 'on');
notes = { 'What this schematic is for', ...
          '', ...
          'The ascent stage is the only part', ...
          'that reaches orbit. It flies on one', ...
          'engine, with no aerodynamic', ...
          'stabilisation and a centre of mass', ...
          'that migrates as the tanks empty.', ...
          'Thrust-to-CoM misalignment turns', ...
          'directly into attitude and', ...
          'injection dispersion.', ...
          '', ...
          'That dispersion is exactly what', ...
          'Part 2 models as a random injection', ...
          'error at the top of the Hohmann', ...
          'climb, and what the HCW hold and the', ...
          'V-bar approach then have to buy', ...
          'back in delta-v.', ...
          '', ...
          'The grapple interface on top is the', ...
          'fixture the 5R arm of Parts 4 and 6', ...
          'captures.' };
for k = 1:numel(notes)
    if k == 1
        col = S.accent; fs = 16; fw = 'bold';
    else
        col = S.dim; fs = 14; fw = 'normal';
    end
    text(ax2, 0.02, 0.96 - 0.048*(k-1), notes{k}, 'Color', col, ...
         'FontName', S.font, 'FontSize', fs, 'FontWeight', fw);
end

outPath = save_fig(fig, 'fig18_lander_schematic', C);
end
