function fig = new_figure(widthPx, heightPx)
%NEW_FIGURE  Off-screen dark figure of a fixed pixel size.
%   fig = NEW_FIGURE(w, h). Always invisible: the whole build must run under
%   `matlab -batch` without a single window popping up or blocking.

if nargin < 1, widthPx  = 1600; end
if nargin < 2, heightPx = 900;  end

S = style();
fig = figure('Color', S.bg, ...
             'Units', 'pixels', ...
             'Position', [1 1 widthPx heightPx], ...
             'Visible', 'off', ...
             'InvertHardcopy', 'off', ...
             'PaperPositionMode', 'auto', ...
             'GraphicsSmoothing', 'on', ...
             'MenuBar', 'none', 'ToolBar', 'none', ...
             'DefaultAxesFontName', S.font, ...
             'DefaultTextFontName', S.font, ...
             'DefaultTextColor', S.text);
end
